In [1]:
import sys, os
modules_path = os.path.abspath('../modules')
if modules_path not in sys.path:
    sys.path.append(modules_path)

import numpy as np
from array import array
import matplotlib.pyplot as plt
from binding import ConcentrationSweep
from partitions import PartitionFunction, Microstates
from time import time

%matplotlib inline
%reload_ext autoreload
%autoreload 2

In [226]:
# parameters (energies in kcal/mole, ordered Pnt-Yan)
a0, b0, c0 = -1, -.5, -1
alpha = [a0*1, a0*2] 
beta = [b0*1, b0*2] 
gamma = [c0*0, c0*0] 

params = dict(alpha=alpha, beta=beta, gamma=gamma)

In [227]:
from partitions import get_ternary_repr, bits_to_int, get_ternary_dim
str_to_array = lambda x: array('I', [int(v) for v in x])

In [230]:
n = 5
microstates = Microstates(Ns=n, params=params, ets=(0,-1))
cms = microstates.get_c_microstates()
energies = cms.get_E()
G = cms.get_G()

In [234]:
x1 = '11111'
arr1 = str_to_array(x1)
k1 = bits_to_int(arr1, len(arr1))

x2 = '12221'
arr2 = str_to_array(x2)
k2 = bits_to_int(arr2, n)

print(G[k1])
print(G[k2])

-3.5
-5.0


In [136]:
'abcdef'[-2]

'e'

In [97]:
get_ternary_repr(k)

NameError: name 'k' is not defined

In [21]:
get_ternary_dim(k)

9

In [22]:
k // (3**10)

0

In [ ]:
np.flo

In [ ]:
min_float = np.finfo(np.float64).min
max_float = np.finfo(np.float64).max
max_float

In [67]:
min_float

-1.7976931348623157e+308

In [31]:
ms = 4
get_ternary_repr(ms)[1]

array('i', [1, 1])

In [32]:
cms.get_a()[:, ms]

array([2, 0])

In [38]:
a = cms.get_a()

for ms in range(3**6):
    ternary = get_ternary_repr(ms)[1]
    if ternary.count(1) != a[0, ms]:
        print('fail')
        
    if ternary.count(2) != a[1, ms]:
        print('fail')

In [ ]:
"""
TODO:


"""

In [119]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [103]:
3**6

729

In [121]:
a = np.arange(20).reshape((2, 10))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [122]:
row_length = 10
for k in range(3, 10):
    for j in range(2):
        val = a.flatten()[j*row_length+k]
        print(val)

3
13
4
14
5
15
6
16
7
17
8
18
9
19


In [85]:
k2

1756792528

In [61]:
int_to_array(x1)

array('I', [1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [31]:
min_int = np.iinfo(np.uint64).min
max_int = np.iinfo(np.uint64).max

In [32]:
3**24

282429536481

In [34]:
n = 48
max_int > (3**n)

False

In [110]:
n, ms = get_ternary_repr(k2)

In [111]:
n

5

In [112]:
ms

array('i', [0, 0, 0, 0, 1, 1])

In [121]:
bits_to_int(ms, n+1)

324

In [120]:
k2

324